# trigger:
# - '*'
 
# pool: Kubernetes

parameters:
- name: str
  type: string
  default: false

# steps:
# - script: echo ${{ parameters.yesNo }}
# stage: Print
# jobs: Print
# - job: Print
#   steps:
#   - script:  echo ${{ parameters.yesNo }}

stages:
- stage:
  jobs: Print
  - job:
    pool: Kubernetes
    steps:
    - script:  echo ${{ parameters.str }}

# name : Print
# trigger:
#   branches:
#     include:
#       - '*'
 
# pool: Kubernetes
 
# variables:
#   ImageName: 'harik8/test:$(Build.BuildId)'
 
# stage: Stage Print
# displayName: Print
# jobs: Job Print
# - job: Print
#   displayName: Print
#   steps:
#   - script: echo $AZP_URL
#     env:
#       AZP_URL: $(AZP_URL)
#   - script: echo $AZP_TOKEN
#     env:
#       AZP_TOKEN: $(AZP_TOKEN)