---
parameters:
  - name: str
    type: string
    default: false
  - name: tag
    type: string
    default: latest
  - name: repo
    type: string
    
variables:
  ${{ if eq(variables['Build.SourceBranchName'], 'main') }}:
    tag: $(major).$(minor).$(patch)
  ${{ else }}:
    tag: $(major).$(minor).$(patch)-${{ parameters.str }}

stages:
- stage:
  variables:
  - group: test
  - name: major
    value: $[variables.major_version]
  - name: minor
    value: $[variables.minor_version]
  - name: patch
    value: $[variables.patch_version]
  pool: Kubernetes
  jobs:
  - job: START
    steps:
      - script: echo ${{ parameters.str }}
      - script: env
  - job: BUILD
    displayName: BUILD IMAGE
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        repository: harik8/test
        containerRegistry: DockerHub
        command: buildAndPush
        dockerfile: "**/Dockerfile"
        tags: |
          ${{variables.tag}}

