---
parameters:
  - name: str
    type: string
    default: false
  - name: tag
    type: string
    default: latest
stages:
  - stage:
    jobs:
      - job: START
        pool: Kubernetes
        steps:
          - script: echo ${{ parameters.str }}
      - job: BUILD
        displayName: BUILD IMAGE
        pool: Kubernetes
        steps:
          - task: Docker@2
            displayName: Build an image
            inputs:
              imageName: harik8/test
              containerRegistry: DockerHub
              command: buildAndPush
              dockerfile: "**/Dockerfile"
              tags: |
                ${{ parameters.tag }}
