---
parameters:
  - name: str
    type: string
    default: false
  - name: tag
    type: string
    default: latest
  - name: repo
    type: string
stages:
  variables:
  - group: ${{ parameters.repo }}
  - name: major
    value: '1'
  - name: minor
    value: '0'
  - name: patch
    value: '0'
  - stage:
    jobs:
      - job: START
        pool: Kubernetes
        steps:
          - script: echo ${{ parameters.str }}
          - script: env
      - job: BUILD
        displayName: BUILD IMAGE
        pool: Kubernetes
        steps:
          - task: Docker@2
            displayName: Build an image
            inputs:
              repository: harik8/test
              containerRegistry: DockerHub
              command: buildAndPush
              dockerfile: "**/Dockerfile"
              tags: |
                ${{ parameters.tag }}-${{ parameters.str }}
